In [6]:
#1.标量
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [10]:
#2向量
x = torch.arange(4)
x



tensor([0, 1, 2, 3])

In [9]:
#向量-通过下标直接访问到任一元素
x[3]

tensor(3)

In [11]:
#长度、维度和形状
#通过调用Python的内置len()函数来访问张量的长度。
len(x)

4

In [12]:
#当用张量表示一个向量（只有一个轴）时，
#我们也可以通过.shape属性访问向量的长度。 
x.shape

torch.Size([4])

In [13]:
#矩阵
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [14]:
#访问矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [15]:
#对称矩阵 = 其转置矩阵
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [16]:
#验证对称矩阵是否等于自己的转置矩阵
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [17]:
# 张量
X = torch.arange(24).reshape(2, 3, 4)#2大个3x4
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [18]:
# 张量算法的基本性质
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [19]:
# 矩阵乘法
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [20]:
# 将张量乘以或加上一个标量不会改变张量的形状，
# 其中张量的每个元素都将与标量相加或相乘

a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [21]:
# 降维
# 计算某元素的和

x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [22]:
# 可以计算任何形状张量的元素和。

A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [23]:
# 为了通过求和所有行的元素来降维（轴0），可以在调用函数时指定axis=0。 
# 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。

#竖着加的 axis = 0
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [24]:
# 指定axis=1将通过汇总所有列的元素降维（轴1）。
# 因此，输入轴1的维数在输出形状中消失。 

A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [25]:
# 沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。
A.sum(axis=[0, 1])  # 结果和A.sum()相同

tensor(190.)

In [26]:
# 可以生成任意形状张量的平均值
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [27]:
# 计算平均值的函数也可以沿指定轴降低张量的维度
A.mean(axis=0), A.sum(axis=0) / A.shape[0]


(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [28]:
# 非降维求和
sum_A = A.sum(axis=1, keepdims=True) #保持轴数不变
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [29]:
# 每一行除以每一行对应的 
# 第一行每个数除以6
# 第二行每个数除以22
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [30]:
# 想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），
# 可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [31]:
# 点积
# 点积（dot product） （或） 是相同位置的按元素乘积的和
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [32]:
# 也可以通过执行按元素乘法，然后进行求和来表示两个向量的点积：
torch.sum(x * y)

tensor(6.)

In [33]:
# 矩阵 - 向量积

# 当我们为矩阵A和向量x调用torch.mv(A, x)时，会执行矩阵-向量积。
# 注意，A的列维数（沿轴1的长度）必须与x的维数（其长度）相同。

A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [34]:
# 矩阵-矩阵乘法
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [35]:
# 范数
# 范数是向量元素平方和的平方根
# L2范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [37]:
torch.abs(u).sum()

tensor(7.)

在深度学习中，我们经常试图解决优化问题： 最大化分配给观测数据的概率; 最小化预测和真实观测之间的距离。 用向量表示物品（如单词、产品或新闻文章），以便最小化相似项目之间的距离，最大化不同项目之间的距离。 目标，或许是深度学习算法最重要的组成部分（除了数据），通常被表达为范数。